<?php $this->headTitle('Download'); ?>

<div class="col-md-12">
	<div id="primary" class="content-area">
		<main class="site-main" role="main">
		<article class="post">
			<header class="entry-header">
				<h1 class="entry-title">Doação</h1>
			</header>
			<div class="entry-summary">

    			<p>Por favor, leia os seguinte termos antes de fazer sua doação:</p>
                <ul>
                    <li>O SystemGunz é um serviço gratuito. Não temos clientes. O servidor é totalmente livre para todos.</li>
                    <li>As doações não são reembolsáveis, se você abrir uma disputa contra nós, será banido.</li>
                    <li>Cada pagamento realizado, por qualquer método de pagamento, será considerado como uma doação.</li>
                    <li>Fazendo uma doação, você receberá como gratificação uma recompensa, isso não é uma compra.</li>
                    <li>Os itens comprados no jogo através da recompensa de doação não serão alterados para outros itens ou movido para outras contas.</li>
                    <li>Nós temos o direito para modificar os itens comprados através da recompensa de doação a qualquer momento.</li>
                    <li>Todos os itens adquiridos através da recompensa de doação são válidos apenas enquanto o servidor se manter.</li>
                </ul>

                <p>Note-se que os jogadores têm total liberdade e você não é obrigado a realizar uma doação para obter itens especiais ou benefícios.
                Os benefícios são apenas uma forma de mostrar gratidão as doadores, que nos ajudam a manter o servidor online.
                Você também pode obter tratamentos especiais ganhando eventos e colaborando com nossa comunidade.</p>

                <p>Doando você concorda que leu e entendeu nossos Termos de Serviço e Regras.</p>

				<div class="text-center">
					<p>
    					<input type="checkbox" name="confirmar" id="confirmar" />
    					<label for="confirmar">Confirmo que li e concordo com os termos para doação</label>
					</p>
                	<button class="btn">Realizar doação <i class="fa fa-check"></i></button>
				</div>
			</div>
		</article>
		</main>
	</div>
</div>
