<div class="zf-table-wrap  form-inline">
    <div class="content">
        <?php foreach($this->rows as $row):?>

		<div class="col-sm-3 col-lg-3 col-md-3">
			<div class="thumbnail">
				<img src="http://placehold.it/300x200" alt="">
				<div class="caption">
					<h4 class="pull-right">$ 5.000</h4>
					<h4>
						<a href="#">Item</a>
					</h4>
					<p>Descrição do item</p>
				</div>
				<div class="ratings">
					<p class="pull-right">15 compras</p>
					<p>
						<span class="glyphicon glyphicon-star"></span>
						<span class="glyphicon glyphicon-star"></span>
						<span class="glyphicon glyphicon-star"></span>
						<span class="glyphicon glyphicon-star"></span>
						<span class="glyphicon glyphicon-star-empty"></span>
					</p>
				</div>
			</div>
		</div>

        <?php endforeach;?>
    </div>
    <?php echo $this->paramsWrap;?>
</div>