<?php $this->headTitle('Carrinho de compras'); ?>

<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading">
			<div class="panel-title">
				<div class="row">
					<div class="col-xs-8">
						<h5>
							<span class="glyphicon glyphicon-shopping-cart"></span> Carrinho de compras
						</h5>
					</div>
					<div class="col-xs-4">
						<button type="button" class="btn btn-primary btn-sm btn-block">
							<span class="glyphicon glyphicon-share-alt"></span> Continuar comprando
						</button>
					</div>
				</div>
			</div>
		</div>
		<div class="panel-body">
		<?php for ($i = 1; $i <= 4; $i++): ?>
			<div class="row">
				<div class="col-xs-2">
					<img class="img-responsive" src="http://placehold.it/100x70">
				</div>
				<div class="col-xs-4">
					<h4 class="product-name">
						<strong>Item <?php echo $i; ?></strong>
					</h4>
					<h4>
						<small>Descrição do item</small>
					</h4>
				</div>
				<div class="col-xs-6">
					<div class="col-xs-6 text-right">
						<h6>
							<strong>4.500 <span class="text-muted">x</span></strong>
						</h6>
					</div>
					<div class="col-xs-4">
						<input type="text" class="form-control input-sm" value="1">
					</div>
					<div class="col-xs-2">
						<button type="button" class="btn btn-link btn-xs">
							<span class="glyphicon glyphicon-trash"> </span>
						</button>
					</div>
				</div>
			</div>
			<hr>
			<?php endfor; ?>
			<div class="row">
				<div class="text-center">
					<div class="col-xs-9">
						<h6 class="text-right"></h6>
					</div>
					<div class="col-xs-3">
						<button type="button" class="btn btn-default btn-sm btn-block">
							Atualiazar carrinho</button>
					</div>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<div class="row text-center">
				<div class="col-xs-9">
					<h4 class="text-right">
						Total <strong>18.000</strong>
					</h4>
				</div>
				<div class="col-xs-3">
					<button type="button" class="btn btn-success btn-block">Finalizar compra</button>
				</div>
			</div>
		</div>
	</div>
</div>