<?php $this->headTitle('Loja'); ?>

<style>
.slide-image {
	width: 100%;
}

.carousel-holder {
	margin-bottom: 30px;
}

.carousel-control, .item {
	border-radius: 4px;
}

.caption {
	height: 100px;
	overflow: hidden;
}

.caption h4 {
	white-space: nowrap;
}

.thumbnail img {
	width: 100%;
}

.ratings {
	padding-right: 10px;
	padding-left: 10px;
	color: #d17581;
}

.thumbnail {
	padding: 0;
}

.thumbnail .caption-full {
	padding: 9px;
	color: #333;
}
</style>

<div class="col-md-3">
	<div class="list-group">
		<?php foreach ($this->categorias as $categoria): ?>
		<a href="#" class="list-group-item"><?php echo $categoria->getNome(); ?></a>
		<?php endforeach; ?>
	</div>

	<a class="btn btn-primary btn-block" href="<?php echo $this->url('site/default', array('controller' => 'loja', 'action' => 'carrinho')); ?>"><span class="glyphicon glyphicon-shopping-cart"></span> Carrinho de compras</a>
</div>

<div class="col-md-9">

	<!-- <div class="row carousel-holder">

		<div class="col-md-12">
			<div id="carousel-example-generic" class="carousel slide"
				data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#carousel-example-generic" data-slide-to="0"
						class="active"></li>
					<li data-target="#carousel-example-generic" data-slide-to="1"></li>
					<li data-target="#carousel-example-generic" data-slide-to="2"></li>
				</ol>
				<div class="carousel-inner">
					<div class="item active">
						<img class="slide-image" src="http://placehold.it/800x300" alt="">
					</div>
					<div class="item">
						<img class="slide-image" src="http://placehold.it/800x300" alt="">
					</div>
					<div class="item">
						<img class="slide-image" src="http://placehold.it/800x300" alt="">
					</div>
				</div>
				<a class="left carousel-control" href="#carousel-example-generic"
					data-slide="prev"> <span class="glyphicon glyphicon-chevron-left"></span>
				</a> <a class="right carousel-control"
					href="#carousel-example-generic" data-slide="next"> <span
					class="glyphicon glyphicon-chevron-right"></span>
				</a>
			</div>
		</div>

	</div> -->
	<div class="row">
		<div id="data-table-shop"></div>
	</div>
</div>

<script>

$(document).ready(function() {
	$('#data-table-shop').zfTable();
});

</script>