<?php $this->headTitle('Download'); ?>

<div class="col-md-12">
	<div id="primary" class="content-area">
		<main class="site-main" role="main">
		<article class="post">
			<header class="entry-header">
				<h1 class="entry-title">Download</h1>
			</header>
			<div class="entry-summary">

				<a class="btn btn-primary" href="#"><i class="fa fa-download"></i> Link 1</a>
				<a class="btn btn-danger" href="#"><i class="fa fa-download"></i> Link 2</a>
				<a class="btn btn-success" href="#"><i class="fa fa-download"></i> Link 3</a>
				<p>&nbsp;</p>
				<table class="table table-bordered">
					<tbody>
						<tr>
							<th>&nbsp;</th>
							<th>Requisitos mínimos</th>
							<th>Requisitos recomendados</th>
						</tr>
						<tr>
							<th>Sistema operacional</th>
							<td colspan="2" class="text-center">Windows XP, Windows Vista, Windows 7, Windows 8</td>
						</tr>
						<tr>
							<th>DirectX</th>
							<td>DirectX 9.0c</td>
							<td>DirectX 9.0c ou acima</td>
						</tr>
						<tr>
							<th>CPU</th>
							<td>Pentium III 500 MHz</td>
							<td>Pentium III 800 MHz+</td>
						</tr>
						<tr>
							<th>RAM</th>
							<td>256 MB</td>
							<td>512 MB ou acima</td>
						</tr>
						<tr>
							<th>Placas de vídeo</th>
							<td>Compatível com Direct 3D</td>
							<td>GeForce 4MX ou superior</td>
						</tr>
						<tr>
							<th>Placas de som</th>
							<td colspan="2" class="text-center">Compatível com Direct3D Sound</td>
						</tr>
						<tr>
							<th>Mouse</th>
							<td colspan="2" class="text-center">Compatível com windows</td>
						</tr>
					</tbody>
				</table>
			</div>
		</article>
		</main>
	</div>
</div>
