<aside class="widget">
	<h1 class="widget-title">Curta-nos no Facebook</h1>
	<div class="fb-page" data-href="https://www.facebook.com/systemgunz"
		data-small-header="false" data-adapt-container-width="true"
		data-hide-cover="false" data-show-facepile="true"
		data-show-posts="false">
		<div class="fb-xfbml-parse-ignore">
			<blockquote cite="https://www.facebook.com/systemgunz">
				<a href="https://www.facebook.com/systemgunz">System Gunz</a>
			</blockquote>
		</div>
	</div>
</aside>