<div class="col-xs-12 col-sm-6">
	<form class="navbar-form navbar-right" role="search" id="login-form">
		<div class="form-group">
			<input type="text" class="form-control" name="login" placeholder="Usuário" required="required">
		</div>
		<div class="form-group">
			<input type="password" class="form-control" name="password" placeholder="Senha" required="required">
		</div>
		<button type="submit" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Realizar login"><i class="fa fa-sign-in"></i></button>
		<button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" title="Esqueceu a senha?"><i class="fa fa-question"></i></button>
	</form>
</div>