<div id="barra_title">
	<p>ÚLTIMAS DO FÓRUM</p>
</div>
<div id="news">
	<div id="news_title">
		<p>Atualizações e novidades</p>
	</div>
	<ul>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
	</ul>
</div>
<div id="news">
	<div id="news_title">
		<p>Últimas postagens</p>
	</div>
	<ul>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
		<li><a href="#">Como ninguém tem coragem de ler as Regras...</a></li>
	</ul>
</div>
<div id="space_15"></div>