<div class="col-md-3">
	<div class="widget widget-default widget-item-icon">
		<div class="widget-item-left">
			<span class="fa fa-users"></span>
		</div>
		<div class="widget-data">
			<div class="widget-int num-count"><?php echo $this->serverStatusTotal; ?></div>
			<div class="widget-title">Jogadores</div>
			<div class="widget-subtitle">Online</div>
		</div>
	</div>                            
</div>
<div class="col-md-3">
	<div class="widget widget-default widget-item-icon">
		<div class="widget-item-left">
			<span class="fa fa-user"></span>
		</div>
		<div class="widget-data">
			<div class="widget-int num-count"><?php echo $this->accountTotal; ?></div>
			<div class="widget-title">Usuários</div>
			<div class="widget-subtitle">Registrados</div>
		</div>
	</div>                            
</div>
<div class="col-md-3">
	<div class="widget widget-default widget-item-icon">
		<div class="widget-item-left">
			<span class="fa fa-male"></span>
		</div>
		<div class="widget-data">
			<div class="widget-int num-count"><?php echo $this->characterTotal; ?></div>
			<div class="widget-title">Personagens</div>
			<div class="widget-subtitle">Criados</div>
		</div>
	</div>                            
</div>
<div class="col-md-3">
	<div class="widget widget-default widget-item-icon">
		<div class="widget-item-left">
			<span class="fa fa-flag"></span>
		</div>
		<div class="widget-data">
			<div class="widget-int num-count"><?php echo $this->clanTotal; ?></div>
			<div class="widget-title">Clãs</div>
			<div class="widget-subtitle">Formados</div>
		</div>
	</div>                            
</div>